export const COOP_CATEGORIES = {
  "Besties": {
    "Shared Housing": [
      "Renovated double-decker bus",
      "1990s mall kiosk turned loft",
      "Tiny-house twin cabins",
      "Beach bungalow over a taco shop",
      "Treehouse with Wi-Fi and lava lamps",
      "Converted Blockbuster store",
      "Skoolie (school bus) with neon underglow",
      "Retro A-frame with shag carpet",
      "Arcade above a laundromat",
      "Warehouse loft with half-pipe",
      "Desert dome with solar disco ball",
      "Boat house that never leaves dock",
      "Y2K bunker with bead curtains",
      "Suburban cul-de-sac castle",
      "Rooftop yurt village",
      "90s sitcom apartment with laugh track"
    ],
    "Dynamic Duo Name": [
      "Salt-N-Peppa 2.0",
      "Kenan & Kel Energy",
      "Tia & Tamera Chaos",
      "Mario & Luigi IRL",
      "Xena & Gabrielle Vibes",
      "Buffy & Willow Patrol",
      "Cher & Dionne Drip",
      "Beavis & Butthead (But Hot)",
      "Bill & Ted’s Finer Adventure",
      "Harold & Kumar (Snack Lords)",
      "Wayne & Garth Reboot",
      "Kim & Ron Possible",
      "Daria & Jane Mood",
      "Mulder & Scully-ish",
      "Zack & Screech (But Functional)",
      "Ash & Pikachu (Friendship OP)"
    ],
    "Shared Pet": [
      "Capybara named Phil",
      "Rescue pit bull named Mixtape",
      "Tamagotchi that refuses to die",
      "Grumpy sphynx cat named Modem",
      "Skateboarding corgi",
      "Chinchilla that loves Ska",
      "Iguana with sunglasses",
      "Goldfish called Beyoncé",
      "Pet rock (limited edition)",
      "Mini pig named Spam",
      "Parrot that yells 'AOL!'",
      "Ferret in a hoodie",
      "Roomba with googly eyes",
      "Hamster named Java",
      "Axolotl named Bubbles",
      "Raccoon that pays rent (sometimes)"
    ],
    "Go-To Hangout City": [
      "Tokyo for arcades",
      "Austin for food trucks",
      "Portland for thrift hauls",
      "Miami for late-night cafecito",
      "Seoul for karaoke booths",
      "New Orleans for beignets",
      "Toronto for festivals",
      "Reykjavík for hot springs",
      "Las Vegas for buffets",
      "San Diego for beach days",
      "New York for bodegas",
      "Chicago for deep-dish diplomacy",
      "London for markets",
      "Mexico City for tacos",
      "Seattle for coffee quests",
      "Honolulu for spam musubi"
    ],
    "Dream Car": [
      "1997 Jeep Wrangler with cassette",
      "DeLorean with cup holders",
      "Cherry red Miata with flip-up lights",
      "Scooby-Doo mystery van dupe",
      "Tesla Cybertruck wrapped in Lisa Frank",
      "Mini Cooper with Pikachu tail",
      "VW bus with beanbag seats",
      "Subaru Outback camping rig",
      "Nissan Skyline poster car",
      "’99 Civic with neon",
      "Kia Soul that blasts Aqua",
      "Hummer H2 irony edition",
      "Convertible Sebring only on Sundays",
      "Rollerblades (budget mode)",
      "E-bike with boombox",
      "Go-kart street-legal (somehow)"
    ],
    "Shared Hobby": [
      "Midnight supermarket Olympics",
      "Thrift-flip fashion battles",
      "Karaoke boy-band duets",
      "Spicy ramen speedruns",
      "Urban geocaching with style",
      "Sneaker drop camping pros",
      "Y2K scrapbooking party",
      "Beach cleanups + burritos",
      "Escape room world tour",
      "Cutting each other’s hair (danger)",
      "Garage band revival",
      "Meme scavenger hunts",
      "Retro console speedrunning",
      "Salsa class then nachos",
      "Neighborhood karaoke cart",
      "Roller rink takeover"
    ],
    "Shared Wealth": [
      "Casually rich from a viral TikTok dance",
      "Sold rare Beanie Baby stash",
      "Won a fast-food Monopoly game",
      "NFT regret fund converted to index",
      "Parents’ Costco points cashed out",
      "Garage sale empire",
      "Start-up exit (dog treat app)",
      "Game show champions",
      "Influencer brand deal with mayonnaise",
      "Flip phones resale fortune",
      "Won settlement vs. evil HOA",
      "Scratch-off miracle",
      "Etsy crochet side-hustle boom",
      "Crypto, but we sold at top somehow",
      "Emergency fund powered by DoorDash",
      "Mailbox-money from ringtone royalties"
    ],
    "Biggest Rival": [
      "That one seagull at the beach",
      "The passive-aggressive barista",
      "Escape room employee named Derek",
      "The HOA newsletter",
      "A rival trivia team called 'Ctrl+W'",
      "Parking enforcement scooter",
      "Duolingo owl (menace)",
      "The claw machine at the arcade",
      "Your ex’s group chat",
      "The karaoke queue hog",
      "Gym treadmill #3",
      "The neighborhood raccoon mafia",
      "The blender at 7am",
      "Group project freeloaders",
      "Ticketmaster fees",
      "Airport TSA shoe policy"
    ]
  },
  "Siblings": {
    "Family Housing Situation": [
      "Bunk-bed ceasefire treaty",
      "Basement lair with lava lamp",
      "Attic split by duct tape line",
      "Shared room, divided by bedsheet",
      "Guest house exile (favorite)",
      "Twin suburban rooms mirror-decor",
      "Grandma’s den turned gamer cave",
      "Garage converted to band studio",
      "RV summers, chaos winters",
      "Couch-surf circuit reward points",
      "Farmhouse with secret tunnels",
      "City apartment with fold-out futon",
      "Top/bottom of duplex rivalry",
      "Swap rooms every birthday",
      "Fort built from moving boxes",
      "Treehouse homework HQ"
    ],
    "Family Car & Keys": [
      "Shared minivan with mystery stain",
      "Hand-me-down Saturn with mixtapes",
      "Dad’s truck (only on Sundays)",
      "Mom’s Prius (gaslighted to 'E')",
      "’98 Corolla with subwoofer",
      "Scooter with sidecar",
      "Skateboard Uber service",
      "BMX bikes with pegs",
      "Y2K Beetle glitter dash",
      "Four-wheeler farm shuttle",
      "Go-kart cul-de-sac king",
      "School bus because detention",
      "Rollerblades + wrist guards",
      "Carpool legend’s SUV",
      "Rusty Jeep with soft top",
      "Unicycle nobody asked for"
    ],
    "Chore You Forever Argue About": [
      "Dishwasher Tetris rules",
      "Taking trash out vs. 'tying it tighter'",
      "Who feeds the dog",
      "Lawn mowing height drama",
      "Laundry mountain ownership",
      "Bathroom science experiments",
      "Dusting trophy shelf",
      "Cleaning the mystery microwave",
      "Windexing the TV like it’s 1999",
      "Vacuum cord wrap technique",
      "Who forgot the dryer lint",
      "Fridge purge science fair",
      "Car crumb crisis",
      "Recycling label detective work",
      "Mopping vs. 'Swiffer counts'",
      "Toilet paper direction war"
    ],
    "Sibling Showdown": [
      "Mario Kart blue-shell etiquette",
      "Nerf war capture the couch",
      "H-O-R-S-E in the driveway",
      "Dance Dance Revolution duel",
      "Who can stay quiet longest (never)",
      "Blind taste test of cereals",
      "Super Soaker standoff",
      "Pillow fort engineering contest",
      "Pog stack domination",
      "UNO reverse masterclass",
      "Arcade ticket hoard-off",
      "Trampoline dodgeball",
      "Tiktok trick-shot challenge",
      "Speed folding fitted sheets",
      "Snap streak endurance",
      "Yard sale haggling champ"
    ],
    "Holiday Tradition": [
      "Matching pajama photo chaos",
      "Microwaved hot cocoa speedrun",
      "Grandpa’s VHS home-movie roast",
      "Couch-bed movie marathon",
      "Turkey bowl with neighbor rivals",
      "White elephant gift sabotage",
      "Snowman with sunglasses",
      "Summer grill Olympics",
      "New Year’s karaoke countdown",
      "Blockbuster marathon reboot night",
      "Waffle breakfast bribe",
      "April Fools’ treaty signing",
      "Pumpkin-spice taste panel",
      "Beach bonfire s’mores math",
      "DIY ornament competition",
      "Sibling Secret Santa chaos"
    ],
    "Prank War Signature Move": [
      "Alarm clock hidden in vent",
      "Fake spider on shower curtain",
      "Changing autocorrect to 'bro'",
      "Frozen cereal prank",
      "Confetti in ceiling fan",
      "Cloned phone background selfie",
      "Toothpaste Oreos classic",
      "Jell-O the remote",
      "Plastic wrap door ambush",
      "Saran-wrapped toilet (cease and desist)",
      "Sneaker in freezer",
      "Auto-play Rickroll",
      "Glitter in backpack (war crime)",
      "TV input swap stealth",
      "Voice assistant sets 4am alarms",
      "Car horn honk string"
    ],
    "Inheritance/Windfall Outcome": [
      "Beanie Baby fortune (surprise)",
      "Timeshare in Daytona (uh oh)",
      "Uncle’s arcade machines",
      "Grandma’s secret cookie stock",
      "Mint-condition trading cards",
      "A boat named 'Midlife Crisis'",
      "Coupon binder worth thousands",
      "VHS collection valuation saga",
      "Rare sneakers vault",
      "Ancient coins no one can appraise",
      "Mystery safe with one sock",
      "Cabin with haunted raccoon",
      "Classic car project forever",
      "Stock dividends from donut chain",
      "Crypto on a lost USB",
      "Music royalties from one ringtone"
    ],
    "Family Pet": [
      "Golden retriever chaos agent",
      "Cat that only loves Grandma",
      "Turtle that outlives everyone",
      "Parakeet that mimics doorbell",
      "Goat that eats homework",
      "Snake named Hiss Hemsworth",
      "Hermit crab escape artist",
      "Bunny who hates wires",
      "Fish with dramatic eye contact",
      "Three-legged legend dog",
      "Hamster named Sir Spins",
      "Lizard with eyebrow vibes",
      "Pigeon who commutes home",
      "Foster fail forever friend",
      "Dog that collects socks",
      "Cat that sits on laptops"
    ]
  },
  "Dating": {
    "First Apartment Vibe": [
      "Exposed brick + plants jungle",
      "Studio with projector bed",
      "Suburban condo IKEA maze",
      "Loft over a donut shop",
      "Tiny home by the lake",
      "Basement speakeasy vibe",
      "High-rise with questionable balcony",
      "Beach shack with sand everywhere",
      "Cabin with vinyl collection",
      "Dorm-core nostalgia pad",
      "Vanlife test run",
      "’90s wallpaper revival",
      "Smart home that glitches",
      "Y2K chrome and glass",
      "Grandma chic doilies",
      "Neighbors with a drum kit"
    ],
    "Two-Career Combo": [
      "One’s a barista, the other’s a meteorologist",
      "One’s a teacher, the other’s a drone racer",
      "One’s a zookeeper, the other’s a UX designer",
      "One’s a park ranger, the other’s a DJ",
      "One’s a paramedic, the other’s a toy inventor",
      "One’s a pastry chef, the other’s a software tester",
      "One’s a plumber, the other’s a travel blogger",
      "One’s a librarian, the other’s a stunt driver",
      "One’s a florist, the other’s a game streamer",
      "One’s a beekeeper, the other’s a lawyer",
      "One’s a carpenter, the other’s a fashion buyer",
      "One’s a marine biologist, the other’s a stand-up comic",
      "One’s a dentist, the other’s a theme-park engineer",
      "One’s a social worker, the other’s a sommelier",
      "One’s a pilot, the other’s a dog groomer",
      "One’s a journalist, the other’s a roboticist"
    ],
    "Date Night Ride": [
      "Used convertible with squeaky top",
      "Scooters lined up like a parade",
      "Rideshare with suspicious glitter",
      "Skateboards hand-holding mode",
      "Electric tandem bike",
      "Borrowed truck with hay",
      "Subway date, same playlist",
      "Rollerblades and knee pads",
      "Moped with baguette rack",
      "Pedicab because whimsy",
      "’90s sedan with CD wallet",
      "Party bus with four strangers",
      "Canoe at sunset",
      "Golf cart around the park",
      "Horse carriage with bluetooth",
      "Walking because vibes"
    ],
    "Meet-Cute Origin": [
      "Grabbed same last pizza slice",
      "Dog leashes tangled at park",
      "Commented on each other’s beanies",
      "Wrong coffee order swap",
      "Matched during a Wi-Fi outage",
      "Escape room teammates",
      "Argued over playlist at party",
      "Reached for same book",
      "Line buddies at theme park",
      "Bumped carts in aisle 5",
      "Rival players in a mobile game",
      "Karaoke mic handoff",
      "Costume party reveal",
      "Return to sender package",
      "Lost AirPod rescue mission",
      "Photo bomb turned DM"
    ],
    "Couple Aesthetic": [
      "Normcore chic",
      "Gorpcore hikers",
      "Y2K chrome glam",
      "Cottagecore picnics",
      "Skater & softie",
      "Streetwear maximalists",
      "’90s sitcom wardrobe",
      "Dark academia cozy",
      "Festival glitter twins",
      "Business casual opposites",
      "Vintage tees & docs",
      "Athleisure royalty",
      "Preppy meets punk",
      "Clean-girl x art-boy",
      "Techwear ninjas",
      "Thrift-store magicians"
    ],
    "Pet Together": [
      "Rescue mutt named Waffles",
      "Plant jungle (names included)",
      "Cat who judges your cooking",
      "Axolotl that waves hello",
      "Two hamsters, one mansion",
      "Foster kittens forever",
      "Beta fish with castle",
      "Adopted senior dog hero",
      "Parrot that ships you",
      "Duck that follows you home",
      "Goat yoga dropout",
      "Hedgehog with tiny hat",
      "Pigeon rehab success",
      "Tortoise that sets the pace",
      "Rabbit who hates chargers",
      "Virtual pet streak since 1998"
    ],
    "City You'll Try": [
      "Denver for sunshine",
      "Brooklyn for bagels",
      "Nashville for music",
      "Vancouver for hikes",
      "Madrid for late dinners",
      "Lisbon for tiles",
      "Melbourne for coffee",
      "Osaka for ramen",
      "Athens for sunsets",
      "Prague for castles",
      "Cape Town for views",
      "Buenos Aires for tango",
      "Copenhagen for bikes",
      "Taipei for night markets",
      "Istanbul for baklava",
      "Marrakesh for souks"
    ],
    "Money Energy": [
      "Ballin’ on coupons",
      "Cash-stuffing envelope pros",
      "Dual-income, Costco-maxxing",
      "Splurge on experiences",
      "Minimalist kings/queens",
      "Freelance feast/famine",
      "Wealth via points hacking",
      "Side-hustle stackers",
      "Full-send investors",
      "Broke but aesthetic",
      "Parents’ phone plan forever",
      "Trust fall fund (tiny trust)",
      "Above-average 401(k) flex",
      "Garage-sale flippers",
      "Ramen now, Europe later",
      "Ritzy when discounted"
    ]
  },
  "Crush": {
    "Meet-Cute Scenario": [
      "Shared umbrella in sudden rain",
      "Same hoodie at thrift rack",
      "Both lost at IKEA",
      "Wrong classroom, right seat",
      "Coffee shop power outlet treaty",
      "Elevator karaoke",
      "Handed each other chapstick",
      "Both waved at wrong person",
      "Escape fire drill buddies",
      "DM reply to meme at 2am",
      "Dog park ball assist",
      "VR headset collision",
      "Dropped phone, perfect catch",
      "Both spilled popcorn",
      "Parallel parking apology",
      "Dance circle hype assist"
    ],
    "Imagined Dual Jobs": [
      "One’s a magician, the other’s a data analyst",
      "One’s a pastry chef, the other’s a parkour coach",
      "One’s a museum curator, the other’s a skate videographer",
      "One’s a mail carrier, the other’s a fashion stylist",
      "One’s a electrician, the other’s a podcast producer",
      "One’s a nurse, the other’s a comic book letterer",
      "One’s a translator, the other’s a beekeeper",
      "One’s a carpenter, the other’s a indie game dev",
      "One’s a barista, the other’s a marine welder",
      "One’s a bus driver, the other’s a sommelier",
      "One’s a yoga teacher, the other’s a meteorologist",
      "One’s a bar owner, the other’s a kindergarten teacher",
      "One’s a electrician, the other’s a wedding planner",
      "One’s a botanist, the other’s a sound engineer",
      "One’s a pilot, the other’s a ceramic artist",
      "One’s a veterinarian, the other’s a stunt double"
    ],
    "Texting Style": [
      "All lowercase, chaotic good",
      "Perfect punctuation, ominous",
      "Memes only, no context",
      "Voice notes over 3 min",
      "GIF diplomacy masters",
      "One-word replies only",
      "Thesis-length paragraphs",
      "Emoji hieroglyphics",
      "Reply in calendar invites",
      "No response, vibes read",
      "Instant replies, then vanish",
      "Typo poetry champions",
      "React-only texters",
      "’90s T9 level speed",
      "All caps enthusiasm",
      "Scheduled texts at 9:00"
    ],
    "First Disaster Date": [
      "Spicy wings, one napkin",
      "Boat tour, instant seasick",
      "Movie with broken AC",
      "Karaoke night with ex’s song",
      "Rain at the outdoor concert",
      "Stuck on escape room step 1",
      "Go-kart tire pops",
      "Arcade eats your tokens",
      "Restaurant 'soft opening' chaos",
      "Haunted house actually haunted",
      "Picnic ants unionize",
      "Mini-golf hole 18 meltdown",
      "Bowling alley cosmic blackout",
      "Mismatched dinner reservations",
      "Food truck ran out",
      "Roller rink DJ no-show"
    ],
    "Concert You Pretend to Like": [
      "1999 boy band comeback",
      "Chaos clowncore EDM",
      "’80s hair metal revival",
      "Indie band with 12 banjos",
      "Skibidi-adjacent meme set",
      "All-kazoo orchestra",
      "Hyperpop at 200 BPM",
      "Fandom you mispronounce",
      "Jazz fusion math set",
      "Country rap hoedown",
      "Scream-o unplugged night",
      "TikTok earworm tour",
      "’90s one-hit wonder fest",
      "Yodeling DJ collab",
      "Silent disco you can’t sync",
      "DJ set that’s just Spotify"
    ],
    "Dream Housing Flex": [
      "Penthouse with slide",
      "Cottage with glass greenhouse",
      "Loft with indoor hammock",
      "Skyscraper pool balcony",
      "Desert villa with stargazing roof",
      "Suburban castle with soft-serve",
      "Ski chalet with hot chocolate tap",
      "Beach house with arcade",
      "Treehouse with rope bridge",
      "Island bungalow with snorkel dock",
      "Y2K chrome penthouse",
      "Victorian with secret passage",
      "Minimalist cube on cliff",
      "Floating house with koi",
      "Converted lighthouse",
      "Library house with ladder"
    ],
    "Future Pet": [
      "Lazy greyhound",
      "Dramatic Siamese cat",
      "Talking parrot rumor",
      "Tarot-reading black cat",
      "Shiba that side-eyes",
      "Mini cow therapist",
      "Snake in a sweater",
      "Ferret with passport",
      "Gecko named Sticky",
      "African grey pun master",
      "Otter (aspirational)",
      "Robo-vac as pet 2",
      "Rescue horse bestie",
      "Chickens named Nugget & Nugget",
      "Pigeon with backpack",
      "Bearded dragon with crown"
    ],
    "Where You Bump Into Them Again": [
      "Target seasonal aisle",
      "Airport security line",
      "Farmers’ market samples",
      "Costco free-sample loop",
      "Bookstore staff picks shelf",
      "Thrift store vinyl bin",
      "Dog beach showdown",
      "Climbing gym chalk cloud",
      "Museum rainy day",
      "Food festival noodle tent",
      "State fair butter sculpture",
      "Comicon in wrong cosplay",
      "Coffee shop last outlet",
      "Subway car 6",
      "Stadium nosebleeds",
      "Voting line civic crush"
    ]
  },
  "Exes": {
    "Post-Breakup Housing": [
      "Crash at cousin’s couch",
      "Studio over a bodega",
      "Room in a gamers’ house",
      "Back to parents, humble arc",
      "Houseboat of reinvention",
      "Micro-loft with giant mirror",
      "New roommate with 3 cats",
      "Vanlife healing tour",
      "Luxury building with sad pool",
      "Dorm-style co-living reset",
      "Suburban spare room saga",
      "Couch-to-couch sabbatical",
      "Airbnb host life",
      "Friend’s art studio corner",
      "Cabin solo retreat",
      "Treehouse quiet mode"
    ],
    "Parallel Careers": [
      "One’s a real-estate agent, the other’s a bike mechanic",
      "One’s a pharmacist, the other’s a surf instructor",
      "One’s a tattoo artist, the other’s a project manager",
      "One’s a financial analyst, the other’s a pastry chef",
      "One’s a stage actor, the other’s a lab tech",
      "One’s a firefighter, the other’s a museum docent",
      "One’s a chiropractor, the other’s a sound designer",
      "One’s a flight attendant, the other’s a carpenter",
      "One’s a bar owner, the other’s a park ranger",
      "One’s a fitness trainer, the other’s a archivist",
      "One’s a social media manager, the other’s a mail carrier",
      "One’s a sushi chef, the other’s a civil engineer",
      "One’s a wedding photographer, the other’s a paramedic",
      "One’s a data scientist, the other’s a florist",
      "One’s a plumber, the other’s a marine biologist",
      "One’s a lawyer, the other’s a glassblower"
    ],
    "Co-Parenting Pet or Plant": [
      "Succulent with joint calendar",
      "Weekend-swap goldendoodle",
      "Every-other-Wednesday gecko",
      "Shared custody betta fish",
      "Hamster timeshare",
      "Rotating litter box duty",
      "Snake with visitation rights",
      "Shared beehive",
      "Co-owned compost worms",
      "Parrot that tattles",
      "Bonsai with notebook",
      "Cat who chose a side",
      "Backyard chickens, odd weeks",
      "Ficus that misses you",
      "Tortoise commute plan",
      "Roomba with alternating charges"
    ],
    "Reason It Ended": [
      "Clashed on pizza pineapple policy",
      "Forgot birthday thrice",
      "Binge-watched ahead",
      "Silent-walker vs. loud-walker",
      "Dog liked one more",
      "Different thermostat religions",
      "Left turns too slow",
      "Texting with only stickers",
      "Didn’t laugh at your memes",
      "Early-bird vs. night-owl war",
      "Borrowed hoodie never returned",
      "Group-chat politics",
      "Spice tolerance mismatch",
      "Vacation planning chaos",
      "Work vs. play imbalance",
      "Clashing Spotify Wrapped"
    ],
    "Who Gets the Ride": [
      "You keep the minivan; I get the mixtapes",
      "Scooter for you, bike for me",
      "I take the hatchback, you the longboard",
      "’02 Tacoma vs. city subway card",
      "Convertible goes to the one with hats",
      "You keep the parking spot",
      "Kayak vs. paddleboard draft",
      "Unicycle nobody wants",
      "You take the electric skateboard",
      "I keep the rollerblades",
      "We sell the car, split the AUX cord",
      "I get the moped, you get the helmet",
      "You Uber; I budget",
      "Bus pass & bike lock bundle",
      "Heelys as consolation prize",
      "Golf cart awarded to the pet parent"
    ],
    "Rebound City": [
      "Miami healing arc",
      "Berlin techno distraction",
      "Mexico City tacos therapy",
      "Lisbon tile-walking",
      "Bangkok street-food sprint",
      "Reykjavík hot-spring reset",
      "Seoul night-market glow",
      "Chicago pizza rebound",
      "Barcelona beach rebrand",
      "Austin live-music detox",
      "Tokyo capsule hotel era",
      "Honolulu surf school",
      "Montreal café recovery",
      "Nashville honky-tonk heal",
      "New Orleans beignet bounce-back",
      "LA hike + farmers’ market arc"
    ],
    "Playlist Division": [
      "You get the sad indie",
      "I keep the gym hype",
      "You take the road trip jams",
      "I get the 90s pop gold",
      "You own the lo-fi beats",
      "I keep the salsa nights",
      "Split the show-tune bangers",
      "Claim the punk; leave the screamo",
      "I keep the throwback hip-hop",
      "You take the EDM drops",
      "You keep the study playlists",
      "I keep the karaoke winners",
      "We fight over the one playlist",
      "Delete the 'our song' quietly",
      "Shuffle custody monthly",
      "Each takes their Wrapped Top 5"
    ],
    "Petty Flex": [
      "Bought a tiny house out of spite",
      "Glowed up with braces",
      "Shared Netflix? Upgraded solo",
      "First-class selfie economy",
      "New plant, who dis",
      "Travel points wizardry",
      "Therapy and a new couch",
      "Gym membership actually used",
      "Sold the ring, got a grill",
      "Launched a newsletter, it paid",
      "Side hustle became main hustle",
      "New haircut changed everything",
      "Found $200 in winter coat",
      "Won the raffle finally",
      "Invested in self-care stocks",
      "Retired the sweatpants"
    ]
  },
  "Married": {
    "Home Base": [
      "Craftsman with squeaky porch swing",
      "Townhouse with friendly neighbors",
      "Farmhouse fixer-upper",
      "Beach condo sand problem",
      "High-rise with stroller elevator",
      "Suburban ranch with pool",
      "Tiny house on big land",
      "City brownstone dream",
      "Mountain cabin retreat",
      "Desert adobe with stars",
      "Lakehouse with dock",
      "Cul-de-sac legend home",
      "Penthouse with baby gate",
      "Duplex with best friends",
      "Converted church with echoes",
      "’90s McMansion renaissance"
    ],
    "Career Combo": [
      "One’s a nurse, the other’s a game developer",
      "One’s a contractor, the other’s a wedding planner",
      "One’s a professor, the other’s a chocolatier",
      "One’s a electrician, the other’s a novelist",
      "One’s a ER doctor, the other’s a museum curator",
      "One’s a chef, the other’s a climate researcher",
      "One’s a pilot, the other’s a kindergarten teacher",
      "One’s a firefighter, the other’s a accountant",
      "One’s a therapist, the other’s a stunt performer",
      "One’s a postal worker, the other’s a fashion buyer",
      "One’s a dental hygienist, the other’s a urban farmer",
      "One’s a travel agent, the other’s a robotics tech",
      "One’s a barista, the other’s a marine biologist",
      "One’s a social worker, the other’s a sound engineer",
      "One’s a paramedic, the other’s a playwright",
      "One’s a librarian, the other’s a drone pilot"
    ],
    "Family Vehicle": [
      "Minivan with snack vault",
      "SUV with crushed goldfish",
      "Wagon with roof box",
      "Pickup with car seats",
      "’90s sedan that won’t die",
      "Electric crossover with crumbs",
      "Cargo van for hobbies",
      "Bike trailer convoy",
      "Hatchback that squeaks",
      "Hybrid with dad stickers",
      "Two-door, bad idea",
      "Golf cart neighborhood hero",
      "School-dropoff shuttle",
      "Carshare life hack",
      "Convertible for date nights",
      "Subaru with dog hair"
    ],
    "Weekend Ritual": [
      "Farmers’ market samples tour",
      "Pancake art championships",
      "Yard sale treasure hunt",
      "Hike then nap",
      "Sports game + nachos",
      "Library story time",
      "Beach cleanups + picnic",
      "DIY project and regret",
      "Family movie fort",
      "Drive-through milkshakes loop",
      "Board-game mega night",
      "Karaoke in the kitchen",
      "Block-party legends",
      "Brunch with stroller parade",
      "Date night grocery run",
      "Bike ride to nowhere"
    ],
    "Pet": [
      "Golden doodle who hugs",
      "Cat who chooses one human",
      "Tortoise, inheritance plan",
      "Parakeets in harmony",
      "Foster dog pipeline",
      "German shepherd lifeguard",
      "Rabbit who decorates cables",
      "Fish hotel aquarium",
      "Bearded dragon named Spike",
      "Hamsters in duplex",
      "Maine coon couch king",
      "Rescued greyhound sprinter",
      "Chicken coop HOA debate",
      "Snake with bedtime story",
      "Pig that hates baths",
      "Goose that guards mail"
    ],
    "Where You Settle": [
      "Near the cool in-laws",
      "Five minutes from tacos",
      "Cul-de-sac capital",
      "Walkable downtown zone",
      "Next to the good school",
      "Near your secret beach",
      "Mountain-town fresh air",
      "College-town forever young",
      "Small town big porch",
      "Urban loft, stroller life",
      "Beach suburb sunsets",
      "Lakeside boardwalk vibes",
      "Desert sunsets cave",
      "Forest cabin neighbors",
      "International adventure hub",
      "Where the coffee is good"
    ],
    "Money Plotline": [
      "Spreadsheet shared since 2019",
      "Envelope system + stickers",
      "Points-hacking vacations",
      "One paycheck, one passion",
      "Two startups, one nap",
      "DIY everything budget",
      "Investment club with friends",
      "Frugal until concert tickets",
      "Side hustles pay daycare",
      "Heirloom coupon binder",
      "Passive income maybe",
      "Cash-only farmers’ market",
      "Crypto curiosity, tiny bag",
      "Big house, small furniture",
      "Renters who travel more",
      "Paid off car victory lap"
    ],
    "Household Quirk": [
      "Label maker on a rampage",
      "Shoes off, socks optional",
      "TV always on subtitles",
      "Themed Thursday dinners",
      "Whiteboard for compliments",
      "Doorbell triggers sing-off",
      "Laundry folded KonMari-ish",
      "Scented candle diplomacy",
      "Thermostat cold war",
      "Two coffee makers",
      "Bowl for rogue LEGO",
      "Plants named like coworkers",
      "Community snack drawer",
      "Everyone has a chore crown",
      "Junk drawer organized (lie)",
      "Mood lighting expert mode"
    ]
  }
}
