export const COOP_CATEGORIES = {
  "Besties": {
    "Where You'll Live": [
      "Renovated double-decker bus",
      "1990s mall kiosk turned loft",
      "Tiny-house twin cabins",
      "Beach bungalow over a taco shop",
      "Treehouse with Wi-Fi and lava lamps",
      "Converted Blockbuster store",
      "Skoolie (school bus) with neon underglow",
      "Retro A-frame with shag carpet",
      "Arcade above a laundromat",
      "Warehouse loft with half-pipe",
      "Desert dome with solar disco ball",
      "Boat house that never leaves dock",
      "Y2K bunker with bead curtains",
      "Suburban cul-de-sac castle",
      "Rooftop yurt village",
      "90s sitcom apartment with laugh track"
    ],
    "Dynamic Duo Name": [
      "Salt-N-Peppa 2.0",
      "Kenan & Kel Energy",
      "Tia & Tamera Chaos",
      "Mario & Luigi IRL",
      "Xena & Gabrielle Vibes",
      "Buffy & Willow Patrol",
      "Cher & Dionne Drip",
      "Beavis & Butthead (But Hot)",
      "Bill & Ted’s Finer Adventure",
      "Harold & Kumar (Snack Lords)",
      "Wayne & Garth Reboot",
      "Kim & Ron Possible",
      "Daria & Jane Mood",
      "Mulder & Scully-ish",
      "Zack & Screech (But Functional)",
      "Ash & Pikachu (Friendship OP)"
    ],
    "Shared Pet": [
      "Capybara named Phil",
      "Rescue pit bull named Mixtape",
      "Tamagotchi that refuses to die",
      "Grumpy sphynx cat named Modem",
      "Skateboarding corgi",
      "Chinchilla that loves Ska",
      "Iguana with sunglasses",
      "Goldfish called Beyoncé",
      "Pet rock (limited edition)",
      "Mini pig named Spam",
      "Parrot that yells 'AOL!'",
      "Ferret in a hoodie",
      "Roomba with googly eyes",
      "Hamster named Java",
      "Axolotl named Bubbles",
      "Raccoon that pays rent (sometimes)"
    ],
    "Go-To Hangout City": [
      "Tokyo for arcades",
      "Austin for food trucks",
      "Portland for thrift hauls",
      "Miami for late-night cafecito",
      "Seoul for karaoke booths",
      "New Orleans for beignets",
      "Toronto for festivals",
      "Reykjavík for hot springs",
      "Las Vegas for buffets",
      "San Diego for beach days",
      "New York for bodegas",
      "Chicago for deep-dish diplomacy",
      "London for markets",
      "Mexico City for tacos",
      "Seattle for coffee quests",
      "Honolulu for spam musubi"
    ],
    "Dream Car": [
      "1997 Jeep Wrangler with cassette",
      "DeLorean with cup holders",
      "Cherry red Miata with flip-up lights",
      "Scooby-Doo mystery van dupe",
      "Tesla Cybertruck wrapped in Lisa Frank",
      "Mini Cooper with Pikachu tail",
      "VW bus with beanbag seats",
      "Subaru Outback camping rig",
      "Nissan Skyline poster car",
      "’99 Civic with neon",
      "Kia Soul that blasts Aqua",
      "Hummer H2 irony edition",
      "Convertible Sebring only on Sundays",
      "Rollerblades (budget mode)",
      "E-bike with boombox",
      "Go-kart street-legal (somehow)"
    ],
    "Shared Hobby": [
      "Midnight supermarket Olympics",
      "Thrift-flip fashion battles",
      "Karaoke boy-band duets",
      "Spicy ramen speedruns",
      "Urban geocaching with style",
      "Sneaker drop camping pros",
      "Y2K scrapbooking party",
      "Beach cleanups + burritos",
      "Escape room world tour",
      "Cutting each other’s hair (danger)",
      "Garage band revival",
      "Meme scavenger hunts",
      "Retro console speedrunning",
      "Salsa class then nachos",
      "Neighborhood karaoke cart",
      "Roller rink takeover"
    ],
    "Shared Wealth": [
      "Casually rich from a viral TikTok dance",
      "Sold rare Beanie Baby stash",
      "Won a fast-food Monopoly game",
      "NFT regret fund converted to index",
      "Parents’ Costco points cashed out",
      "Garage sale empire",
      "Start-up exit (dog treat app)",
      "Game show champions",
      "Influencer brand deal with mayonnaise",
      "Flip phones resale fortune",
      "Won settlement vs. evil HOA",
      "Scratch-off miracle",
      "Etsy crochet side-hustle boom",
      "Crypto, but we sold at top somehow",
      "Emergency fund powered by DoorDash",
      "Mailbox-money from ringtone royalties"
    ],
    "Biggest Rival": [
      "That one seagull at the beach",
      "The passive-aggressive barista",
      "Escape room employee named Derek",
      "The HOA newsletter",
      "A rival trivia team called 'Ctrl+W'",
      "Parking enforcement scooter",
      "Duolingo owl (menace)",
      "The claw machine at the arcade",
      "Your ex’s group chat",
      "The karaoke queue hog",
      "Gym treadmill #3",
      "The neighborhood raccoon mafia",
      "The blender at 7am",
      "Group project freeloaders",
      "Ticketmaster fees",
      "Airport TSA shoe policy"
    ]
  },
  "Siblings": {
    "Family Housing Situation": [
      "Bunk-bed ceasefire treaty",
      "Basement lair with lava lamp",
      "Attic split by duct tape line",
      "Shared room, divided by bedsheet",
      "Guest house exile (favorite)",
      "Twin suburban rooms mirror-decor",
      "Grandma’s den turned gamer cave",
      "Garage converted to band studio",
      "RV summers, chaos winters",
      "Couch-surf circuit reward points",
      "Farmhouse with secret tunnels",
      "City apartment with fold-out futon",
      "Top/bottom of duplex rivalry",
      "Swap rooms every birthday",
      "Fort built from moving boxes",
      "Treehouse homework HQ"
    ],
    "Family Car & Keys": [
      "Shared minivan with mystery stain",
      "Hand-me-down Saturn with mixtapes",
      "Dad’s truck (only on Sundays)",
      "Mom’s Prius (gaslighted to 'E')",
      "’98 Corolla with subwoofer",
      "Scooter with sidecar",
      "Skateboard Uber service",
      "BMX bikes with pegs",
      "Y2K Beetle glitter dash",
      "Four-wheeler farm shuttle",
      "Go-kart cul-de-sac king",
      "School bus because detention",
      "Rollerblades + wrist guards",
      "Carpool legend’s SUV",
      "Rusty Jeep with soft top",
      "Unicycle nobody asked for"
    ],
    "Chore You Forever Argue About": [
      "Dishwasher Tetris rules",
      "Taking trash out vs. 'tying it tighter'",
      "Who feeds the dog",
      "Lawn mowing height drama",
      "Laundry mountain ownership",
      "Bathroom science experiments",
      "Dusting trophy shelf",
      "Cleaning the mystery microwave",
      "Windexing the TV like it’s 1999",
      "Vacuum cord wrap technique",
      "Who forgot the dryer lint",
      "Fridge purge science fair",
      "Car crumb crisis",
      "Recycling label detective work",
      "Mopping vs. 'Swiffer counts'",
      "Toilet paper direction war"
    ],
    "Sibling Showdown": [
      "Mario Kart blue-shell etiquette",
      "Nerf war capture the couch",
      "H-O-R-S-E in the driveway",
      "Dance Dance Revolution duel",
      "Who can stay quiet longest (never)",
      "Blind taste test of cereals",
      "Super Soaker standoff",
      "Pillow fort engineering contest",
      "Pog stack domination",
      "UNO reverse masterclass",
      "Arcade ticket hoard-off",
      "Trampoline dodgeball",
      "Tiktok trick-shot challenge",
      "Speed folding fitted sheets",
      "Snap streak endurance",
      "Yard sale haggling champ"
    ],
    "Holiday Tradition": [
      "Matching pajama photo chaos",
      "Microwaved hot cocoa speedrun",
      "Grandpa’s VHS home-movie roast",
      "Couch-bed movie marathon",
      "Turkey bowl with neighbor rivals",
      "White elephant gift sabotage",
      "Snowman with sunglasses",
      "Summer grill Olympics",
      "New Year’s karaoke countdown",
      "Blockbuster marathon reboot night",
      "Waffle breakfast bribe",
      "April Fools’ treaty signing",
      "Pumpkin-spice taste panel",
      "Beach bonfire s’mores math",
      "DIY ornament competition",
      "Sibling Secret Santa chaos"
    ],
    "Prank War Signature Move": [
      "Alarm clock hidden in vent",
      "Fake spider on shower curtain",
      "Changing autocorrect to 'bro'",
      "Frozen cereal prank",
      "Confetti in ceiling fan",
      "Cloned phone background selfie",
      "Toothpaste Oreos classic",
      "Jell-O the remote",
      "Plastic wrap door ambush",
      "Saran-wrapped toilet (cease and desist)",
      "Sneaker in freezer",
      "Auto-play Rickroll",
      "Glitter in backpack (war crime)",
      "TV input swap stealth",
      "Voice assistant sets 4am alarms",
      "Car horn honk string"
    ],
    "Inheritance/Windfall Outcome": [
      "Beanie Baby fortune (surprise)",
      "Timeshare in Daytona (uh oh)",
      "Uncle’s arcade machines",
      "Grandma’s secret cookie stock",
      "Mint-condition trading cards",
      "A boat named 'Midlife Crisis'",
      "Coupon binder worth thousands",
      "VHS collection valuation saga",
      "Rare sneakers vault",
      "Ancient coins no one can appraise",
      "Mystery safe with one sock",
      "Cabin with haunted raccoon",
      "Classic car project forever",
      "Stock dividends from donut chain",
      "Crypto on a lost USB",
      "Music royalties from one ringtone"
    ],
    "Family Pet": [
      "Golden retriever chaos agent",
      "Cat that only loves Grandma",
      "Turtle that outlives everyone",
      "Parakeet that mimics doorbell",
      "Goat that eats homework",
      "Snake named Hiss Hemsworth",
      "Hermit crab escape artist",
      "Bunny who hates wires",
      "Fish with dramatic eye contact",
      "Three-legged legend dog",
      "Hamster named Sir Spins",
      "Lizard with eyebrow vibes",
      "Pigeon who commutes home",
      "Foster fail forever friend",
      "Dog that collects socks",
      "Cat that sits on laptops"
    ]
  },
  "Dating": {
    "First Apartment Vibe": [
      "Exposed brick + plants jungle",
      "Studio with projector bed",
      "Suburban condo IKEA maze",
      "Loft over a donut shop",
      "Tiny home by the lake",
      "Basement speakeasy vibe",
      "High-rise with questionable balcony",
      "Beach shack with sand everywhere",
      "Cabin with vinyl collection",
      "Dorm-core nostalgia pad",
      "Vanlife test run",
      "’90s wallpaper revival",
      "Smart home that glitches",
      "Y2K chrome and glass",
      "Grandma chic doilies",
      "Neighbors with a drum kit"
    ],
    "Two-Career Combo": [
      "One’s a barista, the other’s a meteorologist",
      "One’s a teacher, the other’s a drone racer",
      "One’s a zookeeper, the other’s a UX designer",
      "One’s a park ranger, the other’s a DJ",
      "One’s a paramedic, the other’s a toy inventor",
      "One’s a pastry chef, the other’s a software tester",
      "One’s a plumber, the other’s a travel blogger",
      "One’s a librarian, the other’s a stunt driver",
      "One’s a florist, the other’s a game streamer",
      "One’s a beekeeper, the other’s a lawyer",
      "One’s a carpenter, the other’s a fashion buyer",
      "One’s a marine biologist, the other’s a stand-up comic",
      "One’s a dentist, the other’s a theme-park engineer",
      "One’s a social worker, the other’s a sommelier",
      "One’s a pilot, the other’s a dog groomer",
      "One’s a journalist, the other’s a roboticist"
    ],
    "Date Night Ride": [
      "Used convertible with squeaky top",
      "Scooters lined up like a parade",
      "Rideshare with suspicious glitter",
      "Skateboards hand-holding mode",
      "Electric tandem bike",
      "Borrowed truck with hay",
      "Subway date, same playlist",
      "Rollerblades and knee pads",
      "Moped with baguette rack",
      "Pedicab because whimsy",
      "’90s sedan with CD wallet",
      "Party bus with four strangers",
      "Canoe at sunset",
      "Golf cart around the park",
      "Horse carriage with bluetooth",
      "Walking because vibes"
    ],
    "Meet-Cute Origin": [
      "Grabbed same last pizza slice",
      "Dog leashes tangled at park",
      "Commented on each other’s beanies",
      "Wrong coffee order swap",
      "Matched during a Wi-Fi outage",
      "Escape room teammates",
      "Argued over playlist at party",
      "Reached for same book",
      "Line buddies at theme park",
      "Bumped carts in aisle 5",
      "Rival players in a mobile game",
      "Karaoke mic handoff",
      "Costume party reveal",
      "Return to sender package",
      "Lost AirPod rescue mission",
      "Photo bomb turned DM"
    ],
    "Couple Aesthetic": [
      "Normcore chic",
      "Gorpcore hikers",
      "Y2K chrome glam",
      "Cottagecore picnics",
      "Skater & softie",
      "Streetwear maximalists",
      "’90s sitcom wardrobe",
      "Dark academia cozy",
      "Festival glitter twins",
      "Business casual opposites",
      "Vintage tees & docs",
      "Athleisure royalty",
      "Preppy meets punk",
      "Clean-girl x art-boy",
      "Techwear ninjas",
      "Thrift-store magicians"
    ],
    "Pet Together": [
      "Rescue mutt named Waffles",
      "Plant jungle (names included)",
      "Cat who judges your cooking",
      "Axolotl that waves hello",
      "Two hamsters, one mansion",
      "Foster kittens forever",
      "Beta fish with castle",
      "Adopted senior dog hero",
      "Parrot that ships you",
      "Duck that follows you home",
      "Goat yoga dropout",
      "Hedgehog with tiny hat",
      "Pigeon rehab success",
      "Tortoise that sets the pace",
      "Rabbit who hates chargers",
      "Virtual pet streak since 1998"
    ],
    "City You'll Try": [
      "Denver for sunshine",
      "Brooklyn for bagels",
      "Nashville for music",
      "Vancouver for hikes",
      "Madrid for late dinners",
      "Lisbon for tiles",
      "Melbourne for coffee",
      "Osaka for ramen",
      "Athens for sunsets",
      "Prague for castles",
      "Cape Town for views",
      "Buenos Aires for tango",
      "Copenhagen for bikes",
      "Taipei for night markets",
      "Istanbul for baklava",
      "Marrakesh for souks"
    ],
    "Money Energy": [
      "Ballin’ on coupons",
      "Cash-stuffing envelope pros",
      "Dual-income, Costco-maxxing",
      "Splurge on experiences",
      "Minimalist kings/queens",
      "Freelance feast/famine",
      "Wealth via points hacking",
      "Side-hustle stackers",
      "Full-send investors",
      "Broke but aesthetic",
      "Parents’ phone plan forever",
      "Trust fall fund (tiny trust)",
      "Above-average 401(k) flex",
      "Garage-sale flippers",
      "Ramen now, Europe later",
      "Ritzy when discounted"
    ]
  },
  "Crush": {
    "Meet-Cute Scenario": [
      "Shared umbrella in sudden rain",
      "Same hoodie at thrift rack",
      "Both lost at IKEA",
      "Wrong classroom, right seat",
      "Coffee shop power outlet treaty",
      "Elevator karaoke",
      "Handed each other chapstick",
      "Both waved at wrong person",
      "Escape fire drill buddies",
      "DM reply to meme at 2am",
      "Dog park ball assist",
      "VR headset collision",
      "Dropped phone, perfect catch",
      "Both spilled popcorn",
      "Parallel parking apology",
      "Dance circle hype assist"
    ],
    "Imagined Dual Jobs": [
      "One’s a magician, the other’s a data analyst",
      "One’s a pastry chef, the other’s a parkour coach",
      "One’s a museum curator, the other’s a skate videographer",
      "One’s a mail carrier, the other’s a fashion stylist",
      "One’s a electrician, the other’s a podcast producer",
      "One’s a nurse, the other’s a comic book letterer",
      "One’s a translator, the other’s a beekeeper",
      "One’s a carpenter, the other’s a indie game dev",
      "One’s a barista, the other’s a marine welder",
      "One’s a bus driver, the other’s a sommelier",
      "One’s a yoga teacher, the other’s a meteorologist",
      "One’s a bar owner, the other’s a kindergarten teacher",
      "One’s a electrician, the other’s a wedding planner",
      "One’s a botanist, the other’s a sound engineer",
      "One’s a pilot, the other’s a ceramic artist",
      "One’s a veterinarian, the other’s a stunt double"
    ],
    "Texting Style": [
      "All lowercase, chaotic good",
      "Perfect punctuation, ominous",
      "Memes only, no context",
      "Voice notes over 3 min",
      "GIF diplomacy masters",
      "One-word replies only",
      "Thesis-length paragraphs",
      "Emoji hieroglyphics",
      "Reply in calendar invites",
      "No response, vibes read",
      "Instant replies, then vanish",
      "Typo poetry champions",
      "React-only texters",
      "’90s T9 level speed",
      "All caps enthusiasm",
      "Scheduled texts at 9:00"
    ],
    "First Disaster Date": [
      "Spicy wings, one napkin",
      "Boat tour, instant seasick",
      "Movie with broken AC",
      "Karaoke night with ex’s song",
      "Rain at the outdoor concert",
      "Stuck on escape room step 1",
      "Go-kart tire pops",
      "Arcade eats your tokens",
      "Restaurant 'soft opening' chaos",
      "Haunted house actually haunted",
      "Picnic ants unionize",
      "Mini-golf hole 18 meltdown",
      "Bowling alley cosmic blackout",
      "Mismatched dinner reservations",
      "Food truck ran out",
      "Roller rink DJ no-show"
    ],
    "Concert You Pretend to Like": [
      "1999 boy band comeback",
      "Chaos clowncore EDM",
      "’80s hair metal revival",
      "Indie band with 12 banjos",
      "Skibidi-adjacent meme set",
      "All-kazoo orchestra",
      "Hyperpop at 200 BPM",
      "Fandom you mispronounce",
      "Jazz fusion math set",
      "Country rap hoedown",
      "Scream-o unplugged night",
      "TikTok earworm tour",
      "’90s one-hit wonder fest",
      "Yodeling DJ collab",
      "Silent disco you can’t sync",
      "DJ set that’s just Spotify"
    ],
    "Dream Housing Flex": [
      "Penthouse with slide",
      "Cottage with glass greenhouse",
      "Loft with indoor hammock",
      "Skyscraper pool balcony",
      "Desert villa with stargazing roof",
      "Suburban castle with soft-serve",
      "Ski chalet with hot chocolate tap",
      "Beach house with arcade",
      "Treehouse with rope bridge",
      "Island bungalow with snorkel dock",
      "Y2K chrome penthouse",
      "Victorian with secret passage",
      "Minimalist cube on cliff",
      "Floating house with koi",
      "Converted lighthouse",
      "Library house with ladder"
    ],
    "Future Pet": [
      "Lazy greyhound",
      "Dramatic Siamese cat",
      "Talking parrot rumor",
      "Tarot-reading black cat",
      "Shiba that side-eyes",
      "Mini cow therapist",
      "Snake in a sweater",
      "Ferret with passport",
      "Gecko named Sticky",
      "African grey pun master",
      "Otter (aspirational)",
      "Robo-vac as pet 2",
      "Rescue horse bestie",
      "Chickens named Nugget & Nugget",
      "Pigeon with backpack",
      "Bearded dragon with crown"
    ],
    "Where You Bump Into Them Again": [
      "Target seasonal aisle",
      "Airport security line",
      "Farmers’ market samples",
      "Costco free-sample loop",
      "Bookstore staff picks shelf",
      "Thrift store vinyl bin",
      "Dog beach showdown",
      "Climbing gym chalk cloud",
      "Museum rainy day",
      "Food festival noodle tent",
      "State fair butter sculpture",
      "Comicon in wrong cosplay",
      "Coffee shop last outlet",
      "Subway car 6",
      "Stadium nosebleeds",
      "Voting line civic crush"
    ]
  },
  "Exes": {
    "Post-Breakup Housing": [
      "Crash at cousin’s couch",
      "Studio over a bodega",
      "Room in a gamers’ house",
      "Back to parents, humble arc",
      "Houseboat of reinvention",
      "Micro-loft with giant mirror",
      "New roommate with 3 cats",
      "Vanlife healing tour",
      "Luxury building with sad pool",
      "Dorm-style co-living reset",
      "Suburban spare room saga",
      "Couch-to-couch sabbatical",
      "Airbnb host life",
      "Friend’s art studio corner",
      "Cabin solo retreat",
      "Treehouse quiet mode"
    ],
    "Parallel Careers": [
      "One’s a real-estate agent, the other’s a bike mechanic",
      "One’s a pharmacist, the other’s a surf instructor",
      "One’s a tattoo artist, the other’s a project manager",
      "One’s a financial analyst, the other’s a pastry chef",
      "One’s a stage actor, the other’s a lab tech",
      "One’s a firefighter, the other’s a museum docent",
      "One’s a chiropractor, the other’s a sound designer",
      "One’s a flight attendant, the other’s a carpenter",
      "One’s a bar owner, the other’s a park ranger",
      "One’s a fitness trainer, the other’s a archivist",
      "One’s a social media manager, the other’s a mail carrier",
      "One’s a sushi chef, the other’s a civil engineer",
      "One’s a wedding photographer, the other’s a paramedic",
      "One’s a data scientist, the other’s a florist",
      "One’s a plumber, the other’s a marine biologist",
      "One’s a lawyer, the other’s a glassblower"
    ],
    "Co-Parenting Pet or Plant": [
      "Succulent with joint calendar",
      "Weekend-swap goldendoodle",
      "Every-other-Wednesday gecko",
      "Shared custody betta fish",
      "Hamster timeshare",
      "Rotating litter box duty",
      "Snake with visitation rights",
      "Shared beehive",
      "Co-owned compost worms",
      "Parrot that tattles",
      "Bonsai with notebook",
      "Cat who chose a side",
      "Backyard chickens, odd weeks",
      "Ficus that misses you",
      "Tortoise commute plan",
      "Roomba with alternating charges"
    ],
    "Reason It Ended": [
      "Clashed on pizza pineapple policy",
      "Forgot birthday thrice",
      "Binge-watched ahead",
      "Silent-walker vs. loud-walker",
      "Dog liked one more",
      "Different thermostat religions",
      "Left turns too slow",
      "Texting with only stickers",
      "Didn’t laugh at your memes",
      "Early-bird vs. night-owl war",
      "Borrowed hoodie never returned",
      "Group-chat politics",
      "Spice tolerance mismatch",
      "Vacation planning chaos",
      "Work vs. play imbalance",
      "Clashing Spotify Wrapped"
    ],
    "Who Gets the Ride": [
      "You keep the minivan; I get the mixtapes",
      "Scooter for you, bike for me",
      "I take the hatchback, you the longboard",
      "’02 Tacoma vs. city subway card",
      "Convertible goes to the one with hats",
      "You keep the parking spot",
      "Kayak vs. paddleboard draft",
      "Unicycle nobody wants",
      "You take the electric skateboard",
      "I keep the rollerblades",
      "We sell the car, split the AUX cord",
      "I get the moped, you get the helmet",
      "You Uber; I budget",
      "Bus pass & bike lock bundle",
      "Heelys as consolation prize",
      "Golf cart awarded to the pet parent"
    ],
    "Rebound City": [
      "Miami healing arc",
      "Berlin techno distraction",
      "Mexico City tacos therapy",
      "Lisbon tile-walking",
      "Bangkok street-food sprint",
      "Reykjavík hot-spring reset",
      "Seoul night-market glow",
      "Chicago pizza rebound",
      "Barcelona beach rebrand",
      "Austin live-music detox",
      "Tokyo capsule hotel era",
      "Honolulu surf school",
      "Montreal café recovery",
      "Nashville honky-tonk heal",
      "New Orleans beignet bounce-back",
      "LA hike + farmers’ market arc"
    ],
    "Playlist Division": [
      "You get the sad indie",
      "I keep the gym hype",
      "You take the road trip jams",
      "I get the 90s pop gold",
      "You own the lo-fi beats",
      "I keep the salsa nights",
      "Split the show-tune bangers",
      "Claim the punk; leave the screamo",
      "I keep the throwback hip-hop",
      "You take the EDM drops",
      "You keep the study playlists",
      "I keep the karaoke winners",
      "We fight over the one playlist",
      "Delete the 'our song' quietly",
      "Shuffle custody monthly",
      "Each takes their Wrapped Top 5"
    ],
    "Petty Flex": [
      "Bought a tiny house out of spite",
      "Glowed up with braces",
      "Shared Netflix? Upgraded solo",
      "First-class selfie economy",
      "New plant, who dis",
      "Travel points wizardry",
      "Therapy and a new couch",
      "Gym membership actually used",
      "Sold the ring, got a grill",
      "Launched a newsletter, it paid",
      "Side hustle became main hustle",
      "New haircut changed everything",
      "Found $200 in winter coat",
      "Won the raffle finally",
      "Invested in self-care stocks",
      "Retired the sweatpants"
    ]
  },
  "Married": {
    "Home Base": [
      "Craftsman with squeaky porch swing",
      "Townhouse with friendly neighbors",
      "Farmhouse fixer-upper",
      "Beach condo sand problem",
      "High-rise with stroller elevator",
      "Suburban ranch with pool",
      "Tiny house on big land",
      "City brownstone dream",
      "Mountain cabin retreat",
      "Desert adobe with stars",
      "Lakehouse with dock",
      "Cul-de-sac legend home",
      "Penthouse with baby gate",
      "Duplex with best friends",
      "Converted church with echoes",
      "’90s McMansion renaissance"
    ],
    "Career Combo": [
      "One’s a nurse, the other’s a game developer",
      "One’s a contractor, the other’s a wedding planner",
      "One’s a professor, the other’s a chocolatier",
      "One’s a electrician, the other’s a novelist",
      "One’s a ER doctor, the other’s a museum curator",
      "One’s a chef, the other’s a climate researcher",
      "One’s a pilot, the other’s a kindergarten teacher",
      "One’s a firefighter, the other’s a accountant",
      "One’s a therapist, the other’s a stunt performer",
      "One’s a postal worker, the other’s a fashion buyer",
      "One’s a dental hygienist, the other’s a urban farmer",
      "One’s a travel agent, the other’s a robotics tech",
      "One’s a barista, the other’s a marine biologist",
      "One’s a social worker, the other’s a sound engineer",
      "One’s a paramedic, the other’s a playwright",
      "One’s a librarian, the other’s a drone pilot"
    ],
    "Family Vehicle": [
      "Minivan with snack vault",
      "SUV with crushed goldfish",
      "Wagon with roof box",
      "Pickup with car seats",
      "’90s sedan that won’t die",
      "Electric crossover with crumbs",
      "Cargo van for hobbies",
      "Bike trailer convoy",
      "Hatchback that squeaks",
      "Hybrid with dad stickers",
      "Two-door, bad idea",
      "Golf cart neighborhood hero",
      "School-dropoff shuttle",
      "Carshare life hack",
      "Convertible for date nights",
      "Subaru with dog hair"
    ],
    "Weekend Ritual": [
      "Farmers’ market samples tour",
      "Pancake art championships",
      "Yard sale treasure hunt",
      "Hike then nap",
      "Sports game + nachos",
      "Library story time",
      "Beach cleanups + picnic",
      "DIY project and regret",
      "Family movie fort",
      "Drive-through milkshakes loop",
      "Board-game mega night",
      "Karaoke in the kitchen",
      "Block-party legends",
      "Brunch with stroller parade",
      "Date night grocery run",
      "Bike ride to nowhere"
    ],
    "Pet": [
      "Golden doodle who hugs",
      "Cat who chooses one human",
      "Tortoise, inheritance plan",
      "Parakeets in harmony",
      "Foster dog pipeline",
      "German shepherd lifeguard",
      "Rabbit who decorates cables",
      "Fish hotel aquarium",
      "Bearded dragon named Spike",
      "Hamsters in duplex",
      "Maine coon couch king",
      "Rescued greyhound sprinter",
      "Chicken coop HOA debate",
      "Snake with bedtime story",
      "Pig that hates baths",
      "Goose that guards mail"
    ],
    "Where You Settle": [
      "Near the cool in-laws",
      "Five minutes from tacos",
      "Cul-de-sac capital",
      "Walkable downtown zone",
      "Next to the good school",
      "Near your secret beach",
      "Mountain-town fresh air",
      "College-town forever young",
      "Small town big porch",
      "Urban loft, stroller life",
      "Beach suburb sunsets",
      "Lakeside boardwalk vibes",
      "Desert sunsets cave",
      "Forest cabin neighbors",
      "International adventure hub",
      "Where the coffee is good"
    ],
    "Money Plotline": [
      "Spreadsheet shared since 2019",
      "Envelope system + stickers",
      "Points-hacking vacations",
      "One paycheck, one passion",
      "Two startups, one nap",
      "DIY everything budget",
      "Investment club with friends",
      "Frugal until concert tickets",
      "Side hustles pay daycare",
      "Heirloom coupon binder",
      "Passive income maybe",
      "Cash-only farmers’ market",
      "Crypto curiosity, tiny bag",
      "Big house, small furniture",
      "Renters who travel more",
      "Paid off car victory lap"
    ],
    "Household Quirk": [
      "Label maker on a rampage",
      "Shoes off, socks optional",
      "TV always on subtitles",
      "Themed Thursday dinners",
      "Whiteboard for compliments",
      "Doorbell triggers sing-off",
      "Laundry folded KonMari-ish",
      "Scented candle diplomacy",
      "Thermostat cold war",
      "Two coffee makers",
      "Bowl for rogue LEGO",
      "Plants named like coworkers",
      "Community snack drawer",
      "Everyone has a chore crown",
      "Junk drawer organized (lie)",
      "Mood lighting expert mode"
    ]
  },
  "Dad & Son": {
    "Garage Project Car": [
      "1969 Camaro (on blocks)",
      "VW Beetle with a surfboard rack",
      "A DeLorean that 'just needs a new flux capacitor'",
      "Old Jeep that's more mud than car",
      "A ridiculously lifted pickup truck",
      "A classic Mini Cooper",
      "A '78 Firebird with a screaming chicken decal",
      "A retired ambulance they'll turn into a camper",
      "A half-finished kit car",
      "A Datsun 240Z with primer patches",
      "A 90s Ford Ranger with a mysterious rattle",
      "A vintage Porsche 914",
      "An old Land Rover that leaks oil",
      "A golf cart they're trying to make street legal",
      "A Geo Metro they're converting to electric",
      "A perfectly fine car they took apart 'to learn'"
    ],
    "Go-To Dad Joke": [
      "'I'm hungry.' 'Hi Hungry, I'm Dad.'",
      "Why don't scientists trust atoms? They make up everything.",
      "What do you call a fake noodle? An Impasta.",
      "I don't trust stairs. They're always up to something.",
      "Did you get a haircut? No, I got them all cut.",
      "What did the ocean say to the beach? Nothing, it just waved.",
      "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
      "What's the best time on a clock? 6:30, hands down.",
      "Why did the scarecrow win an award? He was outstanding in his field.",
      "I'm reading a book on anti-gravity. It's impossible to put down.",
      "I'd tell you a pizza joke, but it's a little cheesy.",
      "Why couldn't the bicycle stand up by itself? It was two tired.",
      "What do you call a fish with no eyes? A fsh.",
      "This is my step-ladder. I never knew my real ladder.",
      "I'm on a seafood diet. I see food, and I eat it.",
      "Why are skeletons so calm? Because nothing gets under their skin."
    ],
    "Yard Work Showdown": [
      "Lawn mowing diagonal vs. horizontal stripes",
      "Who can get the leaf blower started first",
      "Edging the driveway with surgical precision",
      "Weed whacker endurance challenge",
      "Building a 'better' compost pile",
      "Who can stack the firewood the highest",
      "Pressure washing the deck into oblivion",
      "Fertilizer spreader 'art'",
      "Who can find the weirdest thing while raking",
      "The great sprinkler system adjustment debate",
      "Hedge trimming: abstract art vs. military flat-top",
      "Shoveling snow 'the right way'",
      "Mulch spreading speedrun",
      "Who gets to use the riding mower",
      "Gutter cleaning (and who has to climb the ladder)",
      "Debating if a weed is actually a 'rare flower'"
    ],
    "Signature Grilling Move": [
      "The 'Click-Click' of the tongs to assert dominance",
      "The 'one flip only' burger rule",
      "Using a spray bottle of water like a firefighter",
      "The 'it's not burnt, it's caramelized' defense",
      "Wearing a ridiculous apron",
      "Giving everything a 'gentle pat' with the spatula",
      "Telling you the secret ingredient (it's just salt)",
      "Perfect diamond grill marks on a hot dog",
      "Using a beer can to prop up a chicken",
      "Pointing at the grill and saying 'That ain't goin' nowhere'",
      "Testing if it's done by poking it aggressively",
      "An unnecessarily large collection of grill tools",
      "Blaming the charcoal for everything",
      "Insisting on grilling in the rain",
      "The 'let the steak rest' lecture",
      "Serving one single, perfectly cooked sausage first"
    ],
    "Weekend Sports Ritual": [
      "Wearing the 'lucky' unwashed jersey",
      "Yelling at the TV from a specific chair",
      "High-fiving the dog after a good play",
      "Elaborate snack stadium construction",
      "Blaming the refs for everything",
      "Calling the plays 2 seconds before they happen",
      "Muting the commentators to provide their own",
      "Nervous pacing in front of the TV",
      "A victory lap around the living room",
      "The post-game analysis that lasts for hours",
      "Rewinding a single play 15 times",
      "Texting the family group chat in all caps",
      "Recounting 'the good old days' of the team",
      "Making a 'sacrificial' dip that must be eaten",
      "Forbidding anyone from talking during a key moment",
      "Falling asleep by the 3rd quarter"
    ],
    "Shared Piece of 'Wisdom'": [
      "'Measure twice, cut once'",
      "'If it's not broken, don't fix it'",
      "'The early bird gets the worm'",
      "'Righty-tighty, lefty-loosey'",
      "'Work smarter, not harder'",
      "'Always check your oil'",
      "'A penny saved is a penny earned'",
      "'Don't tell your mother'",
      "'If you're gonna be dumb, you gotta be tough'",
      "'Keep your eye on the ball'",
      "'That's how they get you'",
      "'They don't make 'em like they used to'",
      "'It builds character'",
      "'Just needs a little WD-40'",
      "'Look it up on YouTube'",
      "'Ask your mother'"
    ],
    "Tech Support Issue": [
      "The TV input is on the wrong HDMI",
      "The printer isn't printing (it's not on)",
      "Forgetting the password to everything",
      "The computer is 'making a weird noise'",
      "Accidentally changing the TV to Spanish",
      "The mouse isn't working (the battery is dead)",
      "The Wi-Fi is 'broken' (the router is unplugged)",
      "Too many toolbars in the browser",
      "The phone screen is 'too small'",
      "Replying to a scam email",
      "Downloading a virus from a 'free movie' site",
      "The remote control needs new batteries",
      "Can't find 'the Google'",
      "The phone is in airplane mode",
      "His Facebook got 'hacked'",
      "Trying to zoom in on a paper photo"
    ],
    "Vacation Destination Debate": [
      "A historical battlefield tour",
      "A fishing trip with a 5 AM start",
      "A theme park for one single roller coaster",
      "A trip to a hardware store convention",
      "A remote cabin with no Wi-Fi",
      "Going to the beach to 'just sit'",
      "A tour of a famous factory",
      "A road trip with no set destination",
      "Camping in the backyard",
      "A golf-focused resort",
      "Visiting a very specific, obscure museum",
      "A 12-hour drive to 'see the world's largest ball of twine'",
      "Anywhere with a good buffet",
      "A place they went to 30 years ago",
      "The same place you went last year",
      "Nowhere, 'we have a perfectly good house right here'"
    ]
  },
  "Dad & Daughter": {
    "Embarrassing Dance Move": [
      "The Sprinkler",
      "The Shopping Cart",
      "The Lawn Mower",
      "The 'I'm also a cool DJ' knob-turning move",
      "Aggressive finger pointing at the sky",
      "The 'too cool for school' shoulder shrug",
      "An off-beat Running Man",
      "The 'I'm reeling in a big fish' move",
      "The awkward slow dance sway (to a fast song)",
      "The 'check my watch' and 'look at the ceiling' combo",
      "A surprisingly enthusiastic Macarena",
      "The 'stirring a giant pot of soup' move",
      "Snapping his fingers, but slightly off beat",
      "The air guitar solo during the wrong song",
      "A very literal interpretation of 'YMCA'",
      "Just enthusiastic nodding"
    ],
    "Father-Daughter Car Ride Jam": [
      "Bohemian Rhapsody - Queen",
      "Don't Stop Believin' - Journey",
      "Sweet Caroline - Neil Diamond",
      "Livin' on a Prayer - Bon Jovi",
      "Mr. Brightside - The Killers",
      "Anything by Tom Petty",
      "A song from a Disney movie she loved as a kid",
      "That one 90s one-hit wonder",
      "A classic rock song he thinks is 'cool'",
      "A Motown classic",
      "The theme song to a TV show they used to watch",
      "Africa - Toto",
      "Come on Eileen - Dexys Midnight Runners",
      "A Taylor Swift song (he secretly knows all the words)",
      "The local classic rock radio station",
      "Whatever's on, sung very loudly and off-key"
    ],
    "DIY Project Chaos": [
      "Assembling IKEA furniture with 'extra' parts left over",
      "Painting a room and getting more paint on themselves than the walls",
      "Trying to hang a picture frame and making 12 holes",
      "Building a 'simple' bookshelf that ends up crooked",
      "A plumbing 'fix' that results in a minor flood",
      "Planting a garden where nothing grows",
      "Trying to 'fix' an appliance by turning it off and on again",
      "The 'we don't need instructions' approach",
      "A multi-hour trip to the hardware store for one screw",
      "Building a birdhouse that the birds are afraid of",
      "Trying to install a new ceiling fan",
      "A project that requires 'one more tool'",
      "The inevitable 'don't tell your mother about this' moment",
      "Giving up and calling a professional",
      "Deciding to 'build character' by doing it the hard way",
      "Ending the day with a 'well, it has personality' statement"
    ],
    "Protective Dad Trope": [
      "The 'silent, intimidating stare' when meeting a date",
      "The 'what are your intentions?' speech",
      "A 'friendly' but bone-crushing handshake",
      "Casually mentioning his collection of 'tools'",
      "The 'I'll be waiting up' curfew reminder",
      "Asking to see their driving record",
      "The 'just cleaning my shotgun' routine",
      "Following her on social media with a fake account",
      "An 'accidental' drive-by of the date location",
      "Telling embarrassing childhood stories",
      "Asking about their 5-year plan",
      "The 'I know people' threat",
      "Giving a lecture on car maintenance",
      "Insisting on a group hangout first",
      "The 'if you hurt her...' talk",
      "Just a single, raised eyebrow"
    ],
    "Her 'Emergency' Phone Call Reason": [
      "A spider needs to be removed from her room",
      "The car is making a 'weird noise'",
      "She needs help carrying something heavy",
      "She can't open a jar",
      "A question about taxes or 'adulting'",
      "She needs a ride from somewhere",
      "The smoke detector is beeping",
      "She locked her keys in the car",
      "She needs an honest opinion on an outfit",
      "To ask how to cook something simple",
      "She saw a mouse",
      "Her tire pressure light is on",
      "She needs to borrow a tool",
      "To complain about her friends/job/life",
      "She forgot his Netflix password again",
      "Just to say hi (but it sounds like an emergency)"
    ],
    "His Life Advice Topic": [
      "The importance of a firm handshake",
      "How to check your tire pressure",
      "The 'correct' way to mow a lawn",
      "Why you should always have a plunger",
      "The art of negotiating a car price",
      "How to properly grill a steak",
      "The difference between a Phillips and a flathead screwdriver",
      "Why you should save for retirement",
      "How to parallel park",
      "The dangers of cheap tools",
      "A lecture on the stock market (he only owns one stock)",
      "How to change a tire",
      "The importance of good credit",
      "Why [his favorite sports team] is the best",
      "A detailed history of his first car",
      "'Don't get old'"
    ],
    "Shared Hobby 2": [
      "Going to the movies (and debating it for hours after)",
      "Trying new restaurants",
      "Going for long, aimless drives",
      "Building incredibly complex LEGO sets",
      "Watching nature documentaries",
      "Arguing about politics (for fun)",
      "Going to a hardware store 'just to look'",
      "Washing the car",
      "People-watching at the mall",
      "Going to concerts of bands she likes",
      "Playing a board game she always wins",
      "Visiting museums",
      "A shared love for a specific type of dessert",
      "Working on a puzzle together",
      "Going fishing (she just reads a book)",
      "Making fun of the same TV shows"
    ],
    "Annual Tradition": [
      "Going to the same vacation spot every year",
      "The 'Father's Day' tie gift",
      "An argument over how to decorate for a holiday",
      "The ceremonial carving of the Thanksgiving turkey",
      "A trip to a pumpkin patch or apple orchard",
      "Watching the same holiday movie every year",
      "A painfully awkward family photo",
      "The 'back to school' shopping trip",
      "A summer BBQ that he takes way too seriously",
      "A competitive game of mini-golf",
      "Going to a baseball game",
      "The annual 'let's clean the garage' day",
      "A trip to the state fair",
      "A birthday dinner at the same restaurant",
      "Buying and setting up the Christmas tree",
      "Forgetting her birthday until the last minute (jokingly... mostly)"
    ]
  },
  "Mom & Son": {
    "Signature Home-Cooked Meal": [
      "Spaghetti and meatballs from a secret family recipe",
      "Tuna noodle casserole",
      "Meatloaf shaped like a football",
      "'Everything but the kitchen sink' soup",
      "Tacos with exactly three toppings",
      "Chicken pot pie",
      "Perfectly burnt toast, just how he likes it",
      "Lasagna that weighs 15 pounds",
      "Boxed mac and cheese, but 'made with love'",
      "A casserole with a crushed potato chip topping",
      "'Sick day' chicken noodle soup",
      "Grilled cheese and tomato soup",
      "A roast chicken",
      "Pancakes for dinner",
      "Something he hated as a kid but loves now",
      "Whatever was on sale at the grocery store"
    ],
    "His Room's 'Clean' Status": [
      "'Organized chaos'",
      "'I know where everything is'",
      "A biohazard zone",
      "A floor covered in a carpet of clothes",
      "Suspiciously clean (she just cleaned it)",
      "Smells faintly of old pizza and Axe body spray",
      "A museum of empty water bottles",
      "The 'shove everything in the closet' method",
      "A single, sad-looking plant",
      "A chair that is used exclusively for holding clothes",
      "Pristine, because he never leaves the basement",
      "A collection of dusty video game cases",
      "Bed is never made",
      "One clean spot where the dog sleeps",
      "'It's a work in progress'",
      "Clean for exactly one day after she visits"
    ],
    "Her Advice He Ignores": [
      "'You should wear a jacket'",
      "'Don't stay up too late'",
      "'Are you eating enough vegetables?'",
      "'You should call your grandmother more often'",
      "'Maybe you should get a haircut'",
      "'That's not a real job'",
      "'You'll understand when you're older'",
      "'Don't spend all your money in one place'",
      "'You should settle down'",
      "'You should try online dating'",
      "'You're too skinny/fat/tall/short'",
      "'You should be a doctor/lawyer/engineer'",
      "'Don't post that on the internet'",
      "'You should clean your room'",
      "'Just be yourself (but not like that)'",
      "'You should listen to your mother'"
    ],
    "Awkward Public Affection": [
      "Licking her thumb to wipe a smudge off his face",
      "A loud 'I love you, sweetie!' across a crowded room",
      "A too-long hug in front of his friends",
      "Adjusting his collar or hair",
      "Pinching his cheeks",
      "Calling him by a childhood nickname",
      "Showing his baby pictures to his date",
      "Bragging about him too loudly",
      "A kiss on the cheek that leaves a lipstick mark",
      "Trying to hold his hand at the mall",
      "Fixing his posture by poking him in the back",
      "Telling a server it's his birthday when it's not",
      "Asking his friends if they're being good influences",
      "Waving frantically from across the parking lot",
      "A loud, wet kiss on the forehead",
      "An 'I'm so proud of you' speech at an inappropriate time"
    ],
    "'Call Your Mother' Reason": [
      "To ask what he had for lunch",
      "She saw something on the news that 'worried' her",
      "She has a 'quick question' about her computer",
      "A distant relative she hasn't seen in 20 years is sick",
      "She found a coupon for something he might like",
      "She just wanted to 'hear his voice'",
      "To remind him about a holiday that is three months away",
      "She had a dream about him",
      "To ask if he got that package she sent",
      "A weather report for his area",
      "She can't find the remote",
      "To tell him about the neighbor's cat",
      "She forgot what she was going to say",
      "To ask if he's wearing clean underwear",
      "She learned a new piece of gossip",
      "'No reason, just calling!'"
    ],
    "Shared Guilty Pleasure TV Show": [
      "A trashy reality dating show",
      "A cheesy Hallmark Christmas movie",
      "An old black-and-white sitcom",
      "A home renovation show",
      "A cooking competition",
      "A true crime documentary series",
      "A corny sci-fi show from the 90s",
      "A telenovela they watch with subtitles",
      "A show about antiques",
      "A British baking show",
      "A daytime soap opera",
      "A cartoon he used to watch as a kid",
      "A game show with a loud host",
      "A talent competition",
      "A show about finding ghosts",
      "Anything on the Food Network"
    ],
    "Holiday Task He 'Helps' With": [
      "Taste-testing all the food 'for quality control'",
      "Mashing the potatoes (with a handheld mixer)",
      "Carving the turkey (and making a mess)",
      "Setting the table (with the forks on the wrong side)",
      "Being in charge of the 'drinks station'",
      "Taking the trash out at the very end",
      "Entertaining the kids by letting them play video games",
      "Stirring something on the stove for exactly 30 seconds",
      "Opening a stubborn jar",
      "Being the designated 'heavy lifter'",
      "Telling everyone where to park",
      "Making a playlist of 'holiday classics'",
      "Doing the dishes (by loading the dishwasher incorrectly)",
      "Hanging one single, solitary ornament",
      "Getting 'lost' on the way back from the store",
      "Providing 'moral support' from the couch"
    ],
    "The 'Special Occasion' Outfit She Picked": [
      "A sweater with a giant, festive animal on it",
      "A shirt and tie that match perfectly (too perfectly)",
      "A pair of pleated khaki pants",
      "Shoes that are 'sensible' but squeak",
      "A turtleneck in a questionable color",
      "A button-down shirt with a pattern that's 'fun'",
      "A suit that is slightly too big or too small",
      "A pair of 'dress socks' with a cartoon character on them",
      "A handmade sweater that is very, very warm",
      "An outfit that matches what his dad is wearing",
      "A shirt that needs to be ironed (and she will iron it for him)",
      "A 'nice' polo shirt from a brand that was cool 20 years ago",
      "A vest, for some reason",
      "Something she bought 'on sale'",
      "A jacket that doesn't match the pants",
      "The same outfit from last year's family photo"
    ]
  },
  "Mom & Daughter": {
    "Go-To Shopping Destination": [
      "Target, for 'one thing'",
      "HomeGoods, for things you don't need but must have",
      "The clearance rack at a department store",
      "A cute local boutique",
      "The grocery store, but it turns into a 2-hour event",
      "A craft store for a project you'll never finish",
      "A garden center, for 'just one more plant'",
      "A thrift store or consignment shop",
      "The makeup aisle at Sephora or Ulta",
      "A bookstore, to 'just browse'",
      "The farmers' market on a Saturday morning",
      "An antique mall",
      "The mall food court (the shopping is secondary)",
      "A big-box store like Costco for samples",
      "A shoe store with a 'buy one, get one half off' sale",
      "Online, from the comfort of the couch"
    ],
    "Shared Secret Trope": [
      "Hiding a new purchase from Dad",
      "Eating the 'good' snacks when no one is looking",
      "A secret bank account for 'fun money'",
      "Knowing the 'real' story behind a family legend",
      "A secret handshake or code word",
      "Having a favorite child/parent (it's each other)",
      "A pact to always take each other's side in an argument",
      "A hidden stash of chocolate",
      "The 'don't tell your father/brother/sister' pact",
      "Knowing where the 'good' scissors are hidden",
      "A shared, embarrassing childhood memory",
      "A secret recipe that no one else knows",
      "A mutual, unspoken dislike for a certain relative",
      "The 'real' reason the car has a new dent",
      "A secret language of meaningful glances",
      "Agreeing on a TV show to 'hate-watch' together"
    ],
    "Recipe Passed Down (or Not)": [
      "Grandma's chocolate chip cookies (that never taste the same)",
      "A mysterious casserole with a secret ingredient",
      "A holiday pie that is 'the best you'll ever have'",
      "A soup recipe that has 'a little of this, a little of that'",
      "A jello salad from the 1970s",
      "A 'famous' potato salad",
      "A cake recipe with a typo that was never corrected",
      "A dish that is impossible to replicate",
      "A 'shortcut' recipe that is actually much harder",
      "A recipe that exists only in her head",
      "A 'healthy' version of a classic dessert",
      "A dish that requires a very specific, hard-to-find ingredient",
      "A recipe that is 'too easy' but always goes wrong",
      "The 'secret' to perfect gravy",
      "A handwritten recipe card that is barely legible",
      "A recipe that starts with 'first, you make a roux'"
    ],
    "Unsolicited Advice Topic": [
      "Her love life",
      "Her career path",
      "What she's wearing",
      "How she should do her hair",
      "Her posture",
      "The way she loads the dishwasher",
      "Her finances",
      "Her choice of friends",
      "How to drive",
      "Her cooking skills",
      "How she should decorate her apartment",
      "Her social media presence",
      "The importance of thank-you notes",
      "Her sleep schedule",
      "Her exercise routine",
      "Literally everything"
    ],
    "'Borrowed' Closet Item": [
      "A cozy, oversized sweater",
      "A 'vintage' concert t-shirt",
      "A piece of jewelry for a 'special occasion'",
      "A designer handbag",
      "A pair of comfortable shoes",
      "A scarf that 'goes with everything'",
      "A jacket that 'just fits better'",
      "A dress she 'just wanted to try on'",
      "A pair of jeans from 10 years ago",
      "A hat for a sunny day",
      "A formal dress that was worn once",
      "A belt that magically disappeared",
      "A pair of sunglasses",
      "A bridesmaid dress from a wedding",
      "A 'classic' blazer",
      "The 'good' pair of scissors (from the kitchen)"
    ],
    "Gossip Session Fuel": [
      "What the neighbors are up to",
      "A dramatic post on the community Facebook group",
      "An update on a distant relative's life choices",
      "A celebrity scandal",
      "A friend-of-a-friend's recent breakup",
      "A story about someone from her high school",
      "A passive-aggressive comment from another family member",
      "A sale at their favorite store",
      "A new restaurant that just opened",
      "A TV show they're both watching",
      "A critique of someone's recent social media post",
      "The latest royal family drama",
      "A 'can you believe she wore that?' moment",
      "A story that starts with 'you're not going to believe this...'",
      "A detailed analysis of a recent family gathering",
      "Speculation about an upcoming wedding"
    ],
    "DIY Spa Day Activity": [
      "Doing face masks while watching a cheesy movie",
      "Giving each other questionable manicures",
      "Attempting a complicated new hairstyle from a YouTube tutorial",
      "A 'detox' foot bath with weird ingredients",
      "Making a DIY sugar scrub",
      "Plucking each other's eyebrows",
      "Trying out a new, trendy skincare gadget",
      "A 'relaxing' bath with too many bath bombs",
      "Giving each other shoulder rubs",
      "Doing a hair conditioning treatment",
      "Experimenting with a bold new lipstick color",
      "A deep conversation over a cup of herbal tea",
      "Trying (and failing) to do yoga from a video",
      "Giving each other pedicures",
      "Putting cucumbers on your eyes",
      "Just taking a nap"
    ],
    "Generational 'Debate'": [
      "Skinny jeans vs. wide-leg pants",
      "The necessity of the top sheet",
      "Side part vs. middle part",
      "Calling vs. texting",
      "The proper way to use emojis",
      "Is Die Hard a Christmas movie?",
      "The definition of 'clean'",
      "The importance of writing in cursive",
      "Are hot dogs sandwiches?",
      "The use of 'literally'",
      "The Oxford comma",
      "Is cereal a soup?",
      "The correct way to hang toilet paper",
      "The best decade for music",
      "Are leggings pants?",
      "The value of a college degree"
    ]
  }
}